project_dir: '/home/steve/Desktop/projects/noname/ares_project/'
data_dir: '/home/steve/Desktop/projects/noname/ares_project/data/'
models_dir: '/home/steve/Desktop/projects/noname/ares_project/data/models/'
shared_scripts: '/home/steve/Desktop/projects/noname/ares_project/scripts/shared/'
GPU: False
seed: 46282
aminos: [A, D, T, I, V, E, L, Y, P, N, G, S, H, K, R, W, M, Q, F, C, X, B, U, Z, O]
max_sequence_length: 1078
min_sequence_length: 0
training: {
  test_size: 0.22,
  epochs: 10,
  batch_size: 64,
  learning_rate: 0.1
}
prepare_batch: {
  stride: 34,
  padding: 10,
  window_size: 34,
}
CPC: {
  input_sequence_length: 32,
  num_samples: 4,
  num_samples_pos: 1,
  encoding_size: 1,
  code_size: 128,
  rnn_units: 256,
  num_pred_terms: 4,
}
